apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: nginx
    type: nginx-deployment
spec:
  type: NodePort
  selector:
    app: nginx
    type: nginx-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      nodePort: 30007
      
# Deployment starts from here
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    type: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      type: nginx-deployment
  # From now pods data will be taken
  template:
    metadata:
      labels:
        app: nginx
        type: nginx-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.4
        ports:
        - containerPort: 80
  # nodeport starts from here

