apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    type: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      type: nginx-deployment
  # From now pods data will be taken
  template:
    metadata:
      labels:
        app: nginx
        type: nginx-deployment
    spec:
      containers:
      - name: nginx
        image: stable-alpine3.17-perl
        ports:
        - containerPort: 80
