apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    project: John
    app: nginx
    demo: service
  
  spec:
    conatiners:
    - name: nginx-pod
      image: nginx
      ports:
      - containerport: 80


---

apiVersion: v1
kind: service
metadata:
  name: nginx-service
spec:
  selector:
    project: John
    app: nginx
    demo: service
  ports:
  - protocol: TCP
    port: 80
    targetport: 80