apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb
  labels:
    project: John
    app: nginx-lb
    demo: service
  
spec:
  containers:
  - name: nginx-pod
    image: nginx
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nginx-lb-service-01
spec:
  type: LoadBalancer
  selector:
    project: John
    app: nginx-lb
    demo: service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30009